name: whatsapp_tools
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/whatsapp_tools
repository: https://github.com/azkadev/whatsapp_tools
issue_tracker: https://github.com/azkadev/whatsapp_tools/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - whatsapp_tools
#   - whatsapp_tools_flutter
#   - whatsapp_tools_dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
